DRIVER=com.mysql.jdbc.Driver
URL=jdbc:mysql://localhost:3306/sandhiya?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
USER=root
PWD=root
smtp_hostname=smtp.gmail.com
smtp_hostport=465
admin_mailid=satheeskumar.ds@gmail.com
admin_mailpassword=sathees@82